server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rental_Management?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
